---
name: generate-workflows

on:
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - "deployments/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      application_matrix: ${{ steps.matrix.outputs.application_matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2.11.1
        name: Get changed manifests
        id: filter
        with:
          list-files: json
          filters: |
            changes:
              - added|modified: 'deployments/**'
      - id: matrix
        name: Generate application matrix
        run: |
          appnames='${{ steps.filter.outputs.changes_files }}'
          echo "$appnames"
          echo "application_matrix=$appnames" >> $GITHUB_OUTPUT
  call-release-workflow:
    needs: [changes]
    if: ${{ needs.changes.outputs.application_matrix }}
    strategy:
      matrix: ${{ needs.changes.outputs.application_matrix }}
      fail-fast: false
    uses: ./.github/workflows/release.yml
    with:
      appname: ${{ matrix.application }}
