---
name: generate-workflows

on:
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - "deployments/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      application_matrix: ${{ steps.matrix.outputs.application_matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2.11.1
        name: Get changed manifests
        id: filter
        with:
          list-files: shell
          filters: |
            changes:
              - added|modified: 'deployments/**'
      - id: matrix
        name: Generate application matrix
        run: |
          appnames=$(for line in ${{ steps.filter.outputs.changes_files }}; do echo $line | sed -E 's#^deployments/(\w+).*#\1#'; done)
          application_matrix="($appnames)"
          echo "application_matrix=$application_matrix"
          echo "application_matrix=$application_matrix" >> $GITHUB_OUTPUT
  call-release-workflow:
    needs: [changes]
    if: ${{ needs.changes.outputs.application_matrix }}
    strategy:
      matrix: ${{ needs.changes.outputs.application_matrix }}
      fail-fast: false
    uses: ./.github/workflows/release.yml
    with:
      appname: ${{ matrix.application }}
